import React, {useState, useEffect} from "react"
import Popup from "./components/Popup"
import "./index.css"

function App() {

  const [buttonValue, setButtonValue] = useState(false)
  const [timeButtonValue, setTimeButtonValue] = useState(false)
  
useEffect( () => {
  setTimeout (() => {
    setTimeButtonValue(true)
  }, 3000) 
}, [])

  return (
    <div>
        <main>
          <h1> This is the home screen </h1>
          <br/>
          <button onClick={ () => setButtonValue(true)}> This is pop button</button>
        </main>
          <Popup trigger={buttonValue} setTrigger={setButtonValue}>
            <h3> Close this popup</h3>
            <p> This pop up is generated by the button</p>
          </Popup>
          <Popup trigger={timeButtonValue} setTrigger={setTimeButtonValue}>
            <h3> Close this popup</h3>
            <p> This pop up is generated by the time trigger</p>
          </Popup>
    </div>
  );
}

export default App;
